version: '3'

services:
  calc:
    build:
      context: .
      dockerfile: Dockerfile

    network_mode: bridge
    volumes:
      - ./calculator:/calculator
      - ./tmp:/tmp

    # command: sh /make-rating.sh
    entrypoint: tail -f /dev/null