version: '3.6'

services:
  calc:
    build:
      context: .
      dockerfile: Dockerfile


    network_mode: host
    volumes:
      - ./calc:/calc
      - ./tmp:/tmp

    # command: sh /make-rating.sh
    entrypoint: tail -f /dev/null